name: Java CI

on: [push]

jobs:
  BuildJava:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -f ./Lab1CICD/pom.xml --batch-mode --update-snapshots package